// <auto-generated />
using System;
using BlogOnAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogOnAPI.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogOnAPI.Domain.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is a sample post demonstrating CQRS and Vertical Slices.",
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Welcome to the Clean Architecture Blog"
                        },
                        new
                        {
                            Id = 2,
                            Content = "In this post, we explore how MediatR enables the CQRS pattern by separating read and write operations. This separation allows us to optimize each operation independently and maintain cleaner code architecture.",
                            CreatedAt = new DateTime(2024, 1, 5, 10, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Understanding MediatR and CQRS Pattern"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Learn how to implement efficient caching strategies using Redis in ASP.NET Core applications. We'll cover cache invalidation, distributed caching, and performance optimization techniques.",
                            CreatedAt = new DateTime(2024, 1, 10, 14, 15, 0, 0, DateTimeKind.Utc),
                            Title = "Redis Caching Strategies for ASP.NET Core"
                        });
                });

            modelBuilder.Entity("BlogOnAPI.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogPostId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 30, 0, 0, DateTimeKind.Utc),
                            Text = "Great architecture choice!"
                        },
                        new
                        {
                            Id = 2,
                            BlogPostId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 13, 15, 0, 0, DateTimeKind.Utc),
                            Text = "I've been looking for a good example of vertical slice architecture. Thanks for sharing!"
                        },
                        new
                        {
                            Id = 3,
                            BlogPostId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 15, 45, 0, 0, DateTimeKind.Utc),
                            Text = "How does this compare to traditional layered architecture?"
                        },
                        new
                        {
                            Id = 4,
                            BlogPostId = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 9, 20, 0, 0, DateTimeKind.Utc),
                            Text = "Clean and simple implementation. Would love to see more posts like this!"
                        },
                        new
                        {
                            Id = 5,
                            BlogPostId = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 11, 10, 0, 0, DateTimeKind.Utc),
                            Text = "MediatR has really simplified my projects. Great explanation!"
                        },
                        new
                        {
                            Id = 6,
                            BlogPostId = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 14, 25, 0, 0, DateTimeKind.Utc),
                            Text = "Could you elaborate more on the performance implications of using MediatR?"
                        },
                        new
                        {
                            Id = 7,
                            BlogPostId = 2,
                            CreatedAt = new DateTime(2024, 1, 6, 8, 50, 0, 0, DateTimeKind.Utc),
                            Text = "The separation of concerns is fantastic. Makes unit testing so much easier."
                        },
                        new
                        {
                            Id = 8,
                            BlogPostId = 2,
                            CreatedAt = new DateTime(2024, 1, 6, 16, 30, 0, 0, DateTimeKind.Utc),
                            Text = "Do you recommend using the pipeline behaviors for cross-cutting concerns?"
                        },
                        new
                        {
                            Id = 9,
                            BlogPostId = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 15, 5, 0, 0, DateTimeKind.Utc),
                            Text = "Redis has been a game-changer for our application performance!"
                        },
                        new
                        {
                            Id = 10,
                            BlogPostId = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 17, 40, 0, 0, DateTimeKind.Utc),
                            Text = "What's your strategy for cache invalidation in a microservices environment?"
                        },
                        new
                        {
                            Id = 11,
                            BlogPostId = 3,
                            CreatedAt = new DateTime(2024, 1, 11, 10, 15, 0, 0, DateTimeKind.Utc),
                            Text = "Very helpful! I was struggling with distributed caching before reading this."
                        },
                        new
                        {
                            Id = 12,
                            BlogPostId = 3,
                            CreatedAt = new DateTime(2024, 1, 11, 13, 55, 0, 0, DateTimeKind.Utc),
                            Text = "Would be great to see a follow-up on Redis clustering and high availability."
                        });
                });

            modelBuilder.Entity("BlogOnAPI.Domain.Comment", b =>
                {
                    b.HasOne("BlogOnAPI.Domain.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("BlogOnAPI.Domain.BlogPost", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
